apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.nameSpace }}
  name: productpro-liberty-web
  labels:
    app: productpro-liberty-web
spec:
  type: {{ .Values.serviceWeb.type }}
  ports:
    - name: http
      port: 80
      nodePort: {{ .Values.serviceWeb.nodePort }}
      targetPort: {{ .Values.serviceWeb.targetPort }}
  selector:
    app: productpro-liberty-web